import type { Metadata } from "next";
import { APP_CONFIG } from "@/config/app";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "LogMyPlate Terms of Service — rules and conditions for using the app.",
  alternates: { canonical: "/terms" },
};

const lastUpdated = "May 2025";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="flex flex-col gap-4">
      <h2 className="font-display text-xl font-semibold" style={{ color: "var(--text-primary)" }}>
        {title}
      </h2>
      <div
        className="flex flex-col gap-3 text-[15px] leading-relaxed"
        style={{ color: "var(--text-secondary)" }}
      >
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-28 pb-24 px-5 sm:px-6">
      <div className="max-w-2xl mx-auto flex flex-col gap-12">
        {/* Header */}
        <div className="flex flex-col gap-3">
          <p
            className="text-[12px] font-semibold uppercase tracking-widest"
            style={{ color: "#f5a623" }}
          >
            Legal
          </p>
          <h1
            className="font-display text-4xl sm:text-5xl font-bold tracking-tight"
            style={{ color: "var(--text-primary)" }}
          >
            Terms of Service
          </h1>
          <p className="text-[14px]" style={{ color: "var(--text-muted)" }}>
            Last updated: {lastUpdated} · By using LogMyPlate you agree to these terms.
          </p>
          <div
            className="mt-2 rounded-xl p-4 text-[13px] leading-relaxed"
            style={{
              background: "rgba(245,166,35,0.08)",
              border: "1px solid rgba(245,166,35,0.2)",
              color: "var(--text-secondary)",
            }}
          >
            <strong style={{ color: "var(--text-primary)" }}>Note:</strong> These terms are a draft
            prepared by the LogMyPlate engineering team and should be reviewed by a qualified lawyer
            before App Store or Google Play submission.
          </div>
        </div>

        <Section title="1. Acceptance">
          <p>
            By downloading, installing, or using LogMyPlate (the "App"), you agree to be bound by
            these Terms of Service. If you do not agree, do not use the App.
          </p>
        </Section>

        <Section title="2. Description of the service">
          <p>
            LogMyPlate provides AI-powered meal photo analysis that estimates the calorie and
            macronutrient content of food items in a photo. The App is available on iOS and Android
            as a free download, with optional scan credits earned by watching rewarded ads.
          </p>
        </Section>

        <Section title="3. Accounts and authentication">
          <p>
            You may use the App without an account (anonymous mode). If you create an account using
            your email address and a password, you are responsible for keeping your credentials
            secure. You must be at least 13 years old (16 in the EU) to create an account.
          </p>
          <p>We may suspend or terminate accounts that violate these Terms.</p>
        </Section>

        <Section title="4. Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside flex flex-col gap-2 ml-2">
            <li>Use the App for any unlawful purpose</li>
            <li>Attempt to reverse-engineer, decompile, or tamper with the App or its API</li>
            <li>Abuse the scan quota system or attempt to bypass rate limits</li>
            <li>Upload images that are not food photographs in order to manipulate the AI</li>
            <li>Use the App on behalf of a minor under 13 (16 in the EU)</li>
          </ul>
        </Section>

        <Section title="5. AI analysis — disclaimer">
          <p>
            Calorie and macronutrient values provided by LogMyPlate are estimates generated by AI
            models. They are{" "}
            <strong style={{ color: "var(--text-primary)" }}>
              not medically accurate measurements
            </strong>{" "}
            and should not be used for medical, clinical, or therapeutic purposes.
          </p>
          <p>
            Portion sizes are estimated from visual cues in the photo, which is inherently
            imprecise. Actual nutritional content may vary significantly based on preparation
            method, ingredient quality, and portion size.
          </p>
          <p>
            If you have a medical condition requiring precise nutritional tracking, consult a
            registered dietitian or healthcare professional.
          </p>
        </Section>

        <Section title="6. Intellectual property">
          <p>
            The LogMyPlate name, logo, and app design are proprietary. You may not use our
            trademarks without written permission. Your meal journal data remains yours; by using
            the App you grant us a limited licence to process it for the purpose of providing the
            service.
          </p>
        </Section>

        <Section title="7. Rewarded advertising">
          <p>
            LogMyPlate uses Google AdMob to serve rewarded ads. Watching a full rewarded ad unlocks
            additional meal scans. The reward is credited server-side after the ad completion is
            verified. We are not responsible for ad content served by Google&apos;s network.
          </p>
        </Section>

        <Section title="8. Availability and changes">
          <p>
            We reserve the right to modify, suspend, or discontinue the App (or any part of it) at
            any time with or without notice. We will not be liable to you for any modification,
            suspension, or discontinuation.
          </p>
        </Section>

        <Section title="9. Limitation of liability">
          <p>
            To the fullest extent permitted by applicable law, LogMyPlate is provided "as is"
            without warranties of any kind. We are not liable for any indirect, incidental, special,
            or consequential damages arising from your use of the App, including but not limited to
            health outcomes resulting from reliance on AI calorie estimates.
          </p>
        </Section>

        <Section title="10. Governing law">
          <p>
            These Terms are governed by the laws of India. Any disputes arising from use of the App
            will be subject to the exclusive jurisdiction of the courts of India.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            Questions about these Terms? Email us at{" "}
            <a
              href={`mailto:${APP_CONFIG.supportEmail}`}
              className="underline underline-offset-4"
              style={{ color: "#f5a623" }}
            >
              {APP_CONFIG.supportEmail}
            </a>
            .
          </p>
        </Section>
      </div>
    </div>
  );
}
